# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='related', max_length=20)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabelVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='MeancoApp.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('vote_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='NameVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeancoApp.Name')),
            ],
        ),
        migrations.CreateModel(
            name='OfTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('topic_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=1)),
                ('timestamp_last', models.DateTimeField(auto_now=True)),
                ('timestamp_first', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='MeancoApp.Comment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='MeancoApp.Comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentvoters', to='MeancoApp.Profile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='MeancoApp.Version')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('url',), ('label', 'context')]),
        ),
        migrations.AddField(
            model_name='relation',
            name='topic_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_a', to='MeancoApp.Topic'),
        ),
        migrations.AddField(
            model_name='relation',
            name='topic_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_b', to='MeancoApp.Topic'),
        ),
        migrations.AddField(
            model_name='oftopic',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topictags', to='MeancoApp.Profile'),
        ),
        migrations.AddField(
            model_name='oftopic',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='MeancoApp.Tag'),
        ),
        migrations.AddField(
            model_name='oftopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='MeancoApp.Topic'),
        ),
        migrations.AddField(
            model_name='namevoter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeancoApp.Profile'),
        ),
        migrations.AddField(
            model_name='namevoter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeancoApp.Topic'),
        ),
        migrations.AddField(
            model_name='name',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='MeancoApp.Topic'),
        ),
        migrations.AddField(
            model_name='labelvoter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeancoApp.Profile'),
        ),
        migrations.AddField(
            model_name='label',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations', to='MeancoApp.Profile'),
        ),
        migrations.AddField(
            model_name='label',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='MeancoApp.Relation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MeancoApp.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MeancoApp.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set([('profile', 'comment'), ('profile', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('timestamp',)]),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('topic_a', 'topic_b')]),
        ),
        migrations.AlterUniqueTogether(
            name='oftopic',
            unique_together=set([('topic', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='namevoter',
            unique_together=set([('topic', 'profile'), ('profile', 'name'), ('topic', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='name',
            unique_together=set([('topic', 'label')]),
        ),
        migrations.AlterUniqueTogether(
            name='labelvoter',
            unique_together=set([('profile', 'label')]),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('relation', 'text')]),
        ),
    ]
