# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeancoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asd',
        ),
    ]
